"""Benchmarks, baselines, and falsification (paper / evaluation)."""

from pmh.benchmark import (
    ARM_SPECS,
    STANDARD_ARMS,
    ArmRunResult,
    ArmSpec,
    BenchmarkResult,
    BlockPreset,
    SUBTYPE_TO_BLOCK_PRESET,
    ValidationReport,
    benchmark_to_markdown,
    collect_val_embeddings,
    default_geometry_metric,
    get_preset,
    get_subtype_preset,
    list_presets,
    load_benchmark_report,
    normalize_arm,
    resolve_arms,
    run_benchmark_protocol,
    run_sklearn_benchmark,
    run_sklearn_benchmark_multi_seed,
    train_one_arm,
    validate_falsification,
    write_benchmark_report,
)
from pmh.compare import compare_arms, compare_arms_sklearn
from pmh.tdi import (
    TDIReport,
    directional_drift_numpy,
    geometry_report,
    tdi_cls,
    tdi_feature_isotropic,
    tdi_layout,
    trajectory_tdi_encoder,
    trajectory_tdi_layerwise,
)

__all__ = [
    "ARM_SPECS",
    "STANDARD_ARMS",
    "ArmSpec",
    "normalize_arm",
    "resolve_arms",
    "ArmRunResult",
    "BenchmarkResult",
    "run_benchmark_protocol",
    "train_one_arm",
    "benchmark_to_markdown",
    "load_benchmark_report",
    "write_benchmark_report",
    "run_sklearn_benchmark",
    "run_sklearn_benchmark_multi_seed",
    "get_preset",
    "get_subtype_preset",
    "list_presets",
    "SUBTYPE_TO_BLOCK_PRESET",
    "BlockPreset",
    "validate_falsification",
    "ValidationReport",
    "collect_val_embeddings",
    "default_geometry_metric",
    "compare_arms",
    "compare_arms_sklearn",
    "TDIReport",
    "tdi_cls",
    "tdi_layout",
    "tdi_feature_isotropic",
    "trajectory_tdi_layerwise",
    "trajectory_tdi_encoder",
    "directional_drift_numpy",
    "geometry_report",
]
